# .github/workflows/deploy.yaml

name: deploy

on:
  workflow_dispatch:
    inputs:
      cloudflare_project_name:
        description: "The name of the cloudflare project"
        required: true
        type: string
        default: "livscore"

jobs:
  deploy:
    name: deploy release ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yaml
          name: livscore-build
          workflow_conclusion: success
          branch: ${{ github.ref_name }}
          path: dist/

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy out --project-name=${{ inputs.cloudflare_project_name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
